name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  run-int-test:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
#          curl -X POST https://api.github.com/repos/fransah/trigger-service/dispatches \
#          -H 'Accept: application/vnd.github.everest-preview+json' \
#          -u ${{ secrets.ACCESS_TOKEN }} \
#          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'